# Generated by Django 3.1.2 on 2020-10-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20201031_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
